-- MySQL Script generated by MySQL Workbench
-- Thu Jun 29 11:01:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mwold
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mwold
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mwold` DEFAULT CHARACTER SET utf8 ;
USE `mwold` ;

-- -----------------------------------------------------
-- Table `mwold`.`condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mwold`.`condominio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `type` VARCHAR(100) NULL,
  `name_image` VARCHAR(100) NULL,
  `data_image` LONGBLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mwold`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mwold`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(100) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `tipo_usuario` VARCHAR(10) NULL,
  `idcondominio` INT NOT NULL,
  PRIMARY KEY (`id`, `idcondominio`),
  INDEX `fk_usuario_condominio_idx` (`idcondominio` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_condominio`
    FOREIGN KEY (`idcondominio`)
    REFERENCES `mwold`.`condominio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mwold`.`incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mwold`.`incidencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(15) NULL,
  `descripcion` VARCHAR(255) NULL,
  `lugar` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `image` VARCHAR(45) NULL,
  `estatus` INT(1) NULL,
  `idusuario` INT NOT NULL,
  `idcondominio` INT NOT NULL,
  PRIMARY KEY (`id`, `idusuario`, `idcondominio`),
  INDEX `fk_incidencia_usuario1_idx` (`idusuario` ASC, `idcondominio` ASC) VISIBLE,
  UNIQUE INDEX `lugar_UNIQUE` (`lugar` ASC) VISIBLE,
  CONSTRAINT `fk_incidencia_usuario1`
    FOREIGN KEY (`idusuario` , `idcondominio`)
    REFERENCES `mwold`.`usuario` (`id` , `idcondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mwold`.`avisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mwold`.`avisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `aviso` VARCHAR(255) NULL,
  `estatus` TINYINT(1) NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_idcondominio` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_idusuario`, `usuario_idcondominio`),
  INDEX `fk_avisos_usuario1_idx` (`usuario_idusuario` ASC, `usuario_idcondominio` ASC) VISIBLE,
  CONSTRAINT `fk_avisos_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_idcondominio`)
    REFERENCES `mwold`.`usuario` (`id` , `idcondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mwold`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mwold`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `incidencia_idincidencia` INT NOT NULL,
  `incidencia_idusuario` INT NOT NULL,
  `incidencia_idcondominio` INT NOT NULL,
  PRIMARY KEY (`id`, `incidencia_idincidencia`, `incidencia_idusuario`, `incidencia_idcondominio`),
  INDEX `fk_comentarios_incidencia1_idx` (`incidencia_idincidencia` ASC, `incidencia_idusuario` ASC, `incidencia_idcondominio` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_incidencia1`
    FOREIGN KEY (`incidencia_idincidencia` , `incidencia_idusuario` , `incidencia_idcondominio`)
    REFERENCES `mwold`.`incidencia` (`id` , `idusuario` , `idcondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
